## Basic Configuration

baseurl = "https://ebbert.nrw/"
languageCode = "de-de"

author = "Daniel Ebbert"
title = "Daniel Ebbert"

theme = "hugo-goa"

## Site Settings
[params]
author = "Daniel Ebbert"
intro = ""
description = ""
authorimage = "profile.jpg"
dateformat = "Jan 2, 2006"

## Social Accounts
[params.social]
github = "ebbertd"
linkedin = "ebbertd"
email = "contact@ebbert.nrw"

[[menu.main]]
